### ISSUE TITLE
Don't work when add regexpr to url.

### ISSUE THREAD

**Issue by heckad** [hh-h/aiohttp-swagger3#20]
When I use URL like `/api/v1.0/orders/{order_id:\d}/` and trying to send request from swagger I get `curl -X GET"http://localhost:8090/api/v1.0/orders/{order_id:\d}/" -H  "accept: */*"` instead of `curl -X DELETE "http://localhost:8090/api/v1.0/orders/12/" -H  "accept: */*"`.

**Comment by hh-h** [comment]
Please, provide an example with swagger schema.

**Comment by heckad** [comment]
In `examples/docspec/main.py` change endpoint parametrs description in method `get_one_pet` on
```
    parameters:
      - name: pet_id
        in: path
        required: true
        description: The id of the pet to retrieve
        schema:
          type: string
          format: uuid
```
and try to send request with `421af835-0430-4fc3-9e65-53efd1fd163b`. You got 404 and in curl `curl -X GET "http://localhost:8080/pets/{pet_id:[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}}" -H  "accept: application/json"`
