### ISSUE TITLE
Support discriminator

### ISSUE THREAD

**Issue by eLvErDe** [hh-h/aiohttp-swagger3#34]
Hi,

Here is an additional feature that would be awesone:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#discriminatorObject

**Comment by hh-h** [comment]
Hi Adam,

Could you provide a real-world example? I don't get the idea :)

BR

**Comment by eLvErDe** [comment]
Hi,

Instead of using oneOf and validate against any schema, you can define a key in your payload that will decide which schema must validate.
Is that more clear ?

**Comment by hh-h** [comment]
No, I mean I got the idea, but what is the use case? Just to speed up the validation process?
We use it but like this
```yaml
schema1:
  required:
    - type
    ...
  properties:
    type:
      type: string
      enum: [one] <<<
    ...
schema2:
  required:
    - type
  ...
  properties:
    type:
      type: string
      enum: [two] <<<
    ...

oneOf:
  - schema1
  - schema2
```
