### ISSUE TITLE
Deserialize type: string / format: date-time to datetime.datetime ?

### ISSUE THREAD

**Issue by eLvErDe** [hh-h/aiohttp-swagger3#44]
Hello,

I'm pretty surprised the ISO8601 strings are deserialized to string instead of expected datetime.datetime using the following definition:

```yaml
parameters:
  - name: before_dt
    in: query
    description: Filter latest known position before this date
    required: false
    schema:
      type: string
      format: date-time
```

Is that normal ? Do you plan to allow such behavior ?

PS: Sorry I did not try the new version yet but it's definitely on my TODO !

Adam.
