### ISSUE TITLE
Incorrect validation of mixed type array with int and float

### ISSUE THREAD

**Issue by eLvErDe** [hh-h/aiohttp-swagger3#60]
Hello,

Pushing an array with an int inside such payload results in a validation error:  `{"body": {"1": "fail to validate oneOf"}}`

```
      additionalProperties:
        type: array
        items:
          oneOf:
            - type: string
            - type: integer
            - type: number
              format: float
```

Removing integer from oneOf makes parsing works, but the resulting payload contains a float instead of expected integer.

I understand this is "shit" use-case, but JSON spec have different types for int and float so it should work. Maybe it's not allowed by OpenAPI, not sure.

Regards, Adam
